version: "3.8"

services:
  app:
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]